### ISSUE TITLE
Notifications not working Android 10

### ISSUE THREAD

**Issue by mfisher224** [hufman/AndroidAutoIdrive#54]
Tried the app on 2018 X3 with OnePlus 6t running Android 10. Notifications not working. Able to see list of apps but upon entering app controls do not work. Specifically tried with Amazon Music - music plays but unable to skip forward/back and no artwork.

**Comment by hufman** [comment]
Thank you for the report!
I just recently discovered a problem with triggering a popup in IDrive 6, which I believe your car runs. I don't know if I can get popups to work in this version, but I just committed a fix to a crash that happened when the car rejects the popup.
As far as I know, Amazon Music does not allow me to connect with the MediaBrowser API. The next version of the app will support controlling the app through the MediaSession API. If you are running the latest-released 1.1 version, Amazon Music should not be expected to function.
The next version of the app should fix both of these!

**Comment by mfisher224** [comment]
Happy to help test on idrive 6. Let me know how I can help. Great app!!!

**Comment by jezikk82** [comment]
I just tested your today's commits and confirm issue with notification on Android 10 Xiaomi Mi9 (MIUI 11).

I found 3 issues:
- popup notification is not working in Idrive 6 (my2017 and my2019)
- notifications can be viewed only by ConnectedDrive block -> notifications, unfortunately the "Notification" block is not updated unless it's SMS/missed call (but this is delivered independably) 
- I notice another issue that the app have problem with remembering (binding) to notifications service on the phone, even if the app is showing that notifications are on I don't see any in my idrive, I have to go to app, disable notifications in the phone and reenable them to get it back.  Usually that happens when android decide to "exit/kill" app from background work. (back to car after some longer time, couple of hours).

**Comment by hufman** [comment]
@jezikk82 I sincerely appreciate your time in testing this!
I haven't yet figured out a way to get popups working. The official app marks the popup command as deprecated, so perhaps they meant to disable it all along! I plan on having the car read out some or all of the notification when it arrives, to provide some of the benefit from the popup at least.

I found it useful to, within the ConnectedDrive menu, upt the selection over the app's book icon and longpress to assign it to a dashboard shortcut icon. What notifications are you missing? I specifically exclude any notifications that can't be cleared and don't have any actions from the list, but everything else should show up.

The issue about the Notification Service being killed in the background is troubling! I don't have any solution to that, except to point you towards [this guide](https://dontkillmyapp.com/xiaomi) to attempt to relax Xiaomi's background killer.

**Comment by jezikk82** [comment]
I know this type of guides and already set everything according to that. However, sometime it's still happens. I don't have this problem on android 9 Samsung device.

**Comment by mfisher224** [comment]
Tried latest commits today. No longer able to connect. Seems that connectedrive keeps connecting and disconnecting to car. App never able to connect. Idrive6 and android10

**Comment by hufman** [comment]
IDrive is pretty good about sandboxing each individual app from harming any other app, so it's probably just instability in the bridge itself instead of this app.
I've only recently gained access to IDrive 6, and have been testing out the Bluetooth apps functionality, and I saw this disconnect behavior once. My technique to try to fix the connection is to disconnect the Bluetooth and kill the Connected app, turn on Bluetooth and tell the car to connect the Apps connection again. After a minute, the Connected app will show the notification icon saying it is connected, and some 20 seconds later the apps start showing up in the car. Try that and see if it helps!

**Comment by jezikk82** [comment]
I compiled latest version yesterday and I discovered the same issue with connectivity.

Workaround is to disconnected and reconnect phone from idrive level and at the same time having connected app open.

**Comment by mfisher224** [comment]
Yes, that worked for me. Unfortunately once it connected I lost the ability
to make and receive phone calls. My phone no longer shows up in the list of
connected devices even tho the app is working and I can access apps. On the
plus side, Amazon Music works great! On the downside Google Maps just gives
me a blank white map. Hope this helps and happy to help test further.

**Comment by hufman** [comment]
I've noticed that, when connecting to the Apps feature manually, it seems to sometimes only connect the Music and Apps parts, and leaves off the Phone part. Clicking the Phone part should quickly resolve that.

Unfortunately, that is in the car and the Connected app itself, and I don't have much control over that aspect.

**Comment by mfisher224** [comment]
I have been having a lot of connection issues. Tried today and although the phone is connected (calls and bluetooth audio works), the app is unable to connect and the phone does not show up in the list of connected devices in the car. Since it doesn't show up in the car at all, I am unable to try to disconnect/reconnect from idrive.

**Comment by hufman** [comment]
@jezikk82 I think I encountered one of the symptoms you mentioned, where the Notifications list stays empty until you disable/enable the Notification option, and I think it was due to some thread safety issues that I fixed as part of #67. Can you try the latest master revision and see if it helps?

**Comment by hufman** [comment]
I believe the Notifications module has become a lot more robust after some recent refactoring, and the original issue (crashing when launching a popup in idrive 6) was resolved, so I'll close this for now.

**Comment by chriss158** [comment]
As on ID6 no popup is possible, would it be possible to just show the mail icon in the statusbar on new notifications? The mail icon appears when a new mail/sms is received. Maybe this icon can be used.

Keep up the good work 👍

**Comment by hufman** [comment]
That's a great idea! I looked into it a bit, which led to some exciting discoveries that I didn't know about!

The mail icon in the toolbar of the car is related to the Bluetooth MAP (Message Access Profile). It seems that Android unfortunately only exposes the SMS message history over this protocol, and no other notifications. There appear to be some workarounds to get other chat apps to be imported into the SMS history, and then they'll show up in this protocol and thus the official Office/Messaging section of the car. Because it would be generic and work for any car that also uses the Bluetooth MAP protocol, that fits better as a separate app instead of this (IDrive-specific) one.

In order to get the SMS message history (and as a bonus, SMS replying) in the car, the Bluetooth connection has to grant Message Access like this:
![Message Access](https://cdn.thewirecutter.com/wp-content/uploads/2017/10/blog-bluetooth-pairing-android-screenshot-630.png)
I did not know my car even supported this feature with Android, thanks for encouraging me to investigate!

**Comment by chriss158** [comment]
Thanks for investigating 👍 

Yes is used this feature before. There is an app which does exactly the same thing you mentioned. https://play.google.com/store/apps/details?id=org.groebl.sms&hl=de

But i wanted to use only AndroidAutoIdrive because the notifications are much better displayed (eg. with images). The downside is, that the icon in the statusbar is missing. So i don't know if there is any new message.

Using both apps is kind of redundant and i then need to read also the message in the message app of bmw to remove the mail icon in the top.

Let me know if you need help for testing or developing. I'm not that deep into kotlin but maybe i can also help there.

**Comment by jezikk82** [comment]
@chriss158 thx for the link to the app, I tested it today and works nice.
@hufman it'd be great if you could add this functionality to this app.

**Comment by hufman** [comment]
I've been investigating some more, and I think I found some ways to possibly trigger the notification icon in the toolbar. I reverse engineered how the Notification Icon event works and implemented it in a [dev branch](https://github.com/hufman/AndroidAutoIdrive/compare/notification_icon), so if someone with IDrive4 wants to test it out, here's a [dev build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/478/478.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2.1-100-f02ebf3-f02ebf3148106c9dbd81a2abf05f74e49e4ea030-nomap-nonalytics-release.apk)! It _should_ add the Book icon to the toolbar whenever a new notification shows up, and clears the icon away when you view the list of notifications, so please test it out!
My IDrive5 system rejects attempts to show the icon with this method, so I'm still looking for other ways.

**Comment by jezikk82** [comment]
I have idrive5 but would love to test it as soon as u find a solution for that. 
@hufman Are the notifications (in that particular case) shown in Connected Menu or in the Notifications menu iteam ?

**Comment by chriss158** [comment]
> I've been investigating some more, and I think I found some ways to possibly trigger the notification icon in the toolbar. I reverse engineered how the Notification Icon event works and implemented it in a [dev branch](https://github.com/hufman/AndroidAutoIdrive/compare/notification_icon), so if someone with IDrive4 wants to test it out, here's a [dev build](https://androidautoidrive.s3.amazonaws.com/hufman/AndroidAutoIdrive/478/478.1/app/build/outputs/apk/nomapNonalytics/release/androidautoidrive-1.2.1-100-f02ebf3-f02ebf3148106c9dbd81a2abf05f74e49e4ea030-nomap-nonalytics-release.apk)! It _should_ add the Book icon to the toolbar whenever a new notification shows up, and clears the icon away when you view the list of notifications, so please test it out!
> My IDrive5 system rejects attempts to show the icon with this method, so I'm still looking for other ways.

Thanks for your work!

I did a quick test on ID6 before work, and i didn't get a app connection. I will test again after work with the older version so see if it is a problem on my side.

**Comment by hufman** [comment]
@jezikk82 in this version, the list of notifications are contained within the unlabeled book app in the Connected apps section, with no integration to the car's Messages section. The only change so far is adding a book statusbar icon maybe.

@chriss158 Please tap on the Waiting for Connection panel at the bottom to open a view with some connection statuses to help debug. Do you have the latest Connected app installed for your car? This new (not fully relesed or documented) version of my app no longer needs any Classic app installed, so try using just the new Connected app.

**Comment by chriss158** [comment]
I used before a recent master branch version of the app without the classic app installed. But also with this version every once in a while no connection was made. 
Today morning i only installed your linked version and didn't get an app connection. I've tried then to install the classic app to see if it will work then. But it didn't worked. 

This afternoon, after work, it worked immediately (With the installed classic app from this morning).

But sadly no status bar icon appeared  on a new notification :(

**Comment by hufman** [comment]
Oh great, thanks for the test result! I'll keep looking to see how to enable it in newer cars.

The Connected app's Bluetooth support has been flaky sadly. When digging in the recent versions of the apps, it _should_ definitely work if the Connected app is running when the Bluetooth Music connection is made, and toggling the Music connection has worked to establish the connection. Additionally, sometimes the Apps connection in the car isn't enabled for the specific phone even if it was working before, which leads to a unique symptom that I can detect and offer a hint for: The Connected app will show the icon stating it's connected and the BCL tunnel starts connecting, but the BCL tunnel never finishes connecting.
If you are incredibly frustrated and just want it to work, the USB Apps connection seems to be 100% reliable once you enable it in the car.

**Comment by hufman** [comment]
I added #99 for tracking the Notification Icon feature 👍
